name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: snake-server-haxelib
          path: |
            src/
            haxelib.json
            build.hxml
            README.md
            LICENSE
            CHANGELOG.md
          if-no-files-found: error
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - name: Set up Haxelib dependencies
        run: |
          haxelib install dox --quiet
          haxelib install hxargs --quiet
          haxelib install hxcpp --quiet
          haxelib dev snake-server ${{ github.workspace }}
      - name: Build API reference
        working-directory: scripts
        run: haxe docs.hxml
      - uses: actions/upload-artifact@v4
        with:
          name: snake-server-docs
          path: bin/api/
          if-no-files-found: error
      - name: Build targets
        run: |
          haxe neko.hxml
          haxe hl.hxml
          haxe cpp.hxml
